### ISSUE TITLE
Naming Rule Violation en NewBigelowMethod

### ISSUE THREAD

**Issue by danieldiazastudillo** [Gornejo/Bigelow#2]
Según las reglas y normativas de diseño de .NET dictaminan que los métodos, y por sobre todo los estáticos deben empezar con la primera letra mayúscula ([PascalCase](https://chaseonsoftware.com/most-common-programming-case-types/#pascalcase)). El _linter_ de VS2019 alerta al respecto:

![image](https://user-images.githubusercontent.com/14895873/59816388-dfb92980-92e9-11e9-8a54-dc31fce4daec.png)

**Comment by Gornejo** [comment]
Hecho
